#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd)."' ERR
#set -x

((EUID)) && exec sudo -- "$0" "$@"

installScriptCommandTest() {
    testCommand="$1"
    if ! pip_loc="$(type -p "$testCommand")" || [[ -z $pip_loc ]]; then
        pip_needed="true"
    else
        pip_command="$testCommand"
        pip_needed="false"
    fi

}

pip_command=""
pip_needed="true"
if [[ "$pip_needed" == "true" ]]; then
    if ! pip_loc="$(type -p "pip")" || [[ -z $pip_loc ]]; then
        pip_needed="true"
    else
        pip_command="pip"
        pip_needed="false"
    fi
fi
if [[ "$pip_needed" == "true" ]]; then
    if ! pip_loc="$(type -p "pip2")" || [[ -z $pip_loc ]]; then
        pip_needed="true"
    else
        pip_command="pip2"
        pip_needed="false"
    fi
fi
if [[ "$pip_needed" == "true" ]]; then
    if apt install python-pip; then
        pip_needed="true"
    else
        pip_command="pip"
        pip_needed="false"
    fi
fi
