#!/usr/bin/env bash

# Special autodep for ember-shared.

# This file should be sourced rather than run directly.

# Should work without ember-shared (or crystallize), just in case, so don't depend on ember_bash_setup or set traps that need it

#NOTE: MAINTENANCE: Manual error printing
trap 'echo "Error preparing module"; exit 1' ERR

module="$(<support/.module)"
