#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
# set -x

skipConfigFile="false"
if [[ "$1" == "--skip-config-file" ]]; then
    skipConfigFile="true"
    shift
fi

echo 1 "$1" 2 "$2" 3 "$3" 4 "$4" 5 "$5" 6 "$6" 7 "$7" 8 "$8" 9 "$9"
if [[ -n "$1" ]]; then
    crystallizeDestdir="$1"
    shift
fi
if [[ "$1" == "--skip-config-file" ]]; then
    skipConfigFile="true"
    shift
fi
if [[ -n "$1" ]]; then
    crystallizePrefix="$1"
    shift
fi
if [[ -n "$1" ]]; then
    crystallizeCapPrefix="$1"
    shift
fi
if [[ -n "$1" ]]; then
    crystallizeExecPrefix="$1"
    shift
fi
if [[ -n "$1" ]]; then
    crystallizeBindir="$1"
    shift
fi
if [[ -n "$1" ]]; then
    crystallizeDatarootdir="$1"
    shift
fi
if [[ -n "$1" ]]; then
    crystallizeDatadir="$1"
    shift
fi
if [[ -n "$1" ]]; then
    crystallizeSysconfdir="$1"
    shift
fi
if [[ -n "$1" ]]; then
    crystallizeSharedstatedir="$1"
    shift
fi
if ! [[ -n "$crystallizePrefix" ]]; then
    if ! [[ -n "$crystallizeCapPrefix" ]]; then
        crystallizePrefix="$crystallizeDestdir"/usr/local
    else
        crystallizePrefix="$crystallizeCapPrefix"
    fi
fi
echo "crystallizePrefix: $crystallizePrefix"
if ! [[ -n "$crystallizeExecPrefix" ]]; then
    crystallizeExecPrefix="$crystallizePrefix"
fi
echo "crystallizeExecPrefix: $crystallizeExecPrefix"
if ! [[ -n "$crystallizeBindir" ]]; then
    crystallizeBindir="$crystallizeExecPrefix"/bin
fi
echo "crystallizeBindir: $crystallizeBindir"
if ! [[ -n "$crystallizeDatarootdir" ]]; then
    crystallizeDatarootdir="$crystallizePrefix"/share
fi
echo "crystallizeDatarootdir: $crystallizeDatarootdir"
if ! [[ -n "$crystallizeDatadir" ]]; then
    crystallizeDatadir="$crystallizeDatarootdir"
fi
echo "crystallizeDatadir: $crystallizeDatadir"
if ! [[ -n "$crystallizeSysconfdir" ]]; then
    crystallizeSysconfdir="$crystallizePrefix"/etc
fi
echo "crystallizeSysconfdir: $crystallizeSysconfdir"
if ! [[ -n "$crystallizeSharedstatedir" ]]; then
    crystallizeSharedstatedir="$crystallizePrefix"/var
fi
echo "crystallizeSharedstatedir: $crystallizeSharedstatedir"

crystallizeEmberdir="$crystallizePrefix"/Ember\ Library

ereplace "73FAB73B-EEE4-4992-8622-4F3FCEC9823A" "$(date-uuid)" support/crystallize.conf
ereplace "/usr/local/var" "$crystallizeSharedstatedir" support/crystallize.conf
ereplace "/Ember\ Library/" "$crystallizeEmberdir" support/crystallize.conf
ereplace "/usr/local/etc" "$crystallizeSysconfdir" scripts/crystallize-getconf
ereplace "/usr/local/etc" "$crystallizeSysconfdir" scripts/crystallize-logsession

if [[ "$OSTYPE" = darwin* ]]; then
    if ! type "gbash"); then
        emberMacGNUUpgrade
    fi
    find scripts -type f -exec ereplace '#!/usr/bin/env bash' '#!/usr/bin/env gbash'
fi


mkdir -p "$crystallizeBindir"
chmod +x scripts/*
cp scripts/* "$crystallizeBindir/"
if [[ "$skipConfigFile" == "false" ]]; then
    mkdir -p "$crystallizeSysconfdir"
    cp -v support/crystallize.conf "$crystallizeSysconfdir/"
fi
mkdir -p "$crystallizeSharedstatedir"/crystallize
