#!/usr/bin/env bash

# Should work without ember-shared

trap 'echo "Error installing module"; exit 1' ERR

source support/getDirs

mkdir -p "$emberBindir"
cp scripts/ember_bash_setup_core "$emberBindir"
mkdir -p "$emberDatadir"
mkdir "$emberDatadir"/ember-shared/
cp -r data "$emberDatadir"/ember-shared/
if ! [[ -h "$emberDatadir/ember" ]]; then
    ln -s "$emberDatadir/ember-shared/data" "$emberDatadir/ember"
fi
