#!/usr/bin/env bash

if [[ "$OSTYPE" = darwin* ]]; then
    {
        echo '#!/usr/bin/env bash'
        echo 'PATH="${PATH}:/usr/local/bin/"'
        echo 'source ember_bash_setup'
        echo '# eval $(thefuck --alias)'
    } >> /etc/bashrc
fi
