#!/usr/bin/env bash

{
    echo '#!/usr/bin/env bash'
    echo 'PATH="${PATH}:/usr/local/bin/"'
    echo 'source ember_bash_setup'
    echo '# eval $(thefuck --alias)'
} >> /etc/bashrc
echo "/usr/local/bin/bash" >> /etc/shells
chsh -s /usr/local/bin/bash "$USER"
