#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
set -x

if [[ "$OSTYPE" = darwin* ]]; then
    if ! type "greadlink"; then
        scripts/emberMacGNUUpgrade
    fi
    find scripts -type f -exec bash -c "source ember_bash_setup &> /dev/null; perl -0777 -p -i -e '\''s/readlink /greadlink /g'\'' \"\$0\"" {} \;
    find scripts -type f -exec bash -c "source ember_bash_setup &> /dev/null; perl -0777 -p -i -e '\''s/sort /gsort /g'\'' \"\$0\"" {} \;
    find scripts -type f -exec bash -c "source ember_bash_setup &> /dev/null; perl -0777 -p -i -e '\''s/du /gdu /g'\'' \"\$0\"" {} \;
    find scripts -type f -exec bash -c "source ember_bash_setup &> /dev/null; perl -0777 -p -i -e '\''s/sed /gsed /g'\'' \"\$0\"" {} \;
fi
