#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
#set -x

if [[ "$OSTYPE" = darwin* ]]; then
    if ! type "greadlink"; then
        scripts/emberMacGNUUpgrade
    fi
    find scripts -type f -exec bash -c "ereplace 'readlink ' 'greadlink '" \;
    find scripts -type f -exec bash -c "ereplace 'sort ' 'gsort '" \;
    find scripts -type f -exec bash -c "ereplace 'du ' 'gdu '" \;
fi
