#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO}."' ERR
#set -x

if [[ "$OSTYPE" = darwin* ]]; then
    if ! type "greadlink"; then
        scripts/emberMacGNUUpgrade
    fi
    find scripts -type f -exec bash -c "source ember_bash_setup &> /dev/null; ereplace 'readlink ' 'greadlink ' \"$1\"" {} \;
    find scripts -type f -exec bash -c "source ember_bash_setup &> /dev/null; ereplace 'sort ' 'gsort '\"$1\"" {} \;
    find scripts -type f -exec bash -c "source ember_bash_setup &> /dev/null; ereplace 'du ' 'gdu '\"$1\"" {} \;
fi
