#!/usr/bin/env bash

#set -x

app="$1"
shift

if [[ "$OSTYPE" = darwin* ]]; then
    if ! [[ -e "$(which "g$app")" ]]; then
        echo "Please run emberMacGNUInstall, and then restart your command."
        sudo brew install coreutils findutils gnu-tar gnu-sed gawk gnutls gnu-indent gnu-getopt
    else
        exec "g$app" "$@"
    fi
else
    exec "$app" "$@"
fi
