#!/usr/bin/env bash
# shellcheck disable=SC1091

#set -x

app="$1"
shift

if [[ "$OSTYPE" = darwin* ]]; then
    if ! [[ -e "$(which "g$app")" ]]; then
        backslashes
    else
        exec "g$app" "$@"
    fi
else
    exec "$app" "$@"
fi
