#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

((EUID)) && exec sudo -- "$0" "$@"

if [[ "srsync" == "$1" ]]; then
    borg with-lock "$(ember-getconf BorgLocation)" srsync /Ember/EmberLibraryBorg /Ember/ember-library-2/ || die
    cd /Ember/ember-library-2/ || die
    eogup-single || die
    exit 0
fi

trap 'error-notify "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."; exit 1' ERR

BORG_PASSPHRASE="$(ember-getconf BorgPassphrase)"
export BORG_PASSPHRASE

borg config "$(ember-getconf BorgLocation)" append_only 1 &>/dev/null || true

action="$1"
shift
case $action in
init)
    mkdir -p "$(ember-getconf BorgLocation)"
    mkdir -p "$(ember-getconf BorgMountpoint)"
    borg init --encryption=repokey "$(ember-getconf BorgLocation)"
    borg config "$(ember-getconf BorgLocation)" append_only 1
    ;;
savequick)
    tempA="$(tempFile)"
    tempB="$(tempFile)"
    tempC="$(tempFile)"
    pwd > "$tempA"
    printf '%s\0' "$@" > "$tempB"
    emdate > "$tempC"
    # FIXME hardcoded username
    borg create --stats --progress --list --filter=AME --compression 'lzma,6' "$(ember-getconf BorgLocation)"'::'"$(emdate)" "$tempA" "$tempB" "$tempC" ~/.bash_history /home/kyan/.bash_history "$@"
    ;;
save)
    tempA="$(tempFile)"
    tempB="$(tempFile)"
    tempC="$(tempFile)"
    pwd > "$tempA"
    printf '%s\0' "$@" > "$tempB"
    emdate > "$tempC"
    borg create --stats --progress --list --filter=AME --compression 'lzma,6' --files-cache disabled "$(ember-getconf BorgLocation)"'::'"$(emdate)" "$tempA" "$tempB" "$tempC" ~/.bash_history /home/kyan/.bash_history "$@"
    ;;
mount)
    borg mount -o allow_other "$(ember-getconf BorgLocation)" "$(ember-getconf BorgMountpoint)"
    ;;
umount)
    borg umount "$(ember-getconf BorgMountpoint)"
    ;;
status)
    borg info "$(ember-getconf BorgLocation)"
    ;;
check)
    borg check -v -p --verify-data "$(ember-getconf BorgLocation)"
    ;;
sync)
    borg with-lock "$(ember-getconf BorgLocation)" srsync /Ember/EmberLibraryBorg /Ember/ember-library-2/
    cd /Ember/ember-library-2/
    eogup-single
    ;;
*)
    echo "Unknown action."
    exit 1
    ;;
esac
