#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

update=""
if [[ "$1" == "--update" ]]; then
    update="true"
    shift
fi

emberPath="$(ember-getconf EmberLibrary)"
cd "$emberPath"/ember-web-site
if [[ "$update" == "true" ]]; then
    "$emberPath"/futuramerlin-web-toolkit/scripts/futuramerlin-web-toolkit-build
fi

cd futuramerlin-web-toolkit-output

php -S localhost:8000
