#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

if [[ -z "$1" ]]; then
    sudo echo
    sudo cp "$0" "$0.tmp"
    exec "$0.tmp" --innerExec
else
    installDir="$(tempDir)"
    (
        cd "$installDir" || die "cd failed"

        git clone https://github.com/ethus3h/ember-shared.git
        (
            cd ember-shared || die "cd failed"
            ./configure
            make
            sudo make noconf
            make autodep
        )
    )
    rm -rf "${installDir:?}"
fi
