#!/usr/bin/env bash
#set -x

#NOTE: MAINTENANCE: Manual error printing
if [[ -z "$(ember-getconf emberSharedVersion)" ]]; then
    printf '%b' '\033[1;31m' >&2
    echo "ERROR: ember-shared is not properly installed! It must be installed to use Crystallize." >&2
    printf '%b' '\033[0m' >&2
    exit 1
fi

ember-getconf "$@"
