#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

((EUID)) && exec sudo -- "$0" "$@"

trap 'error-notify "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."; exit 1' ERR

action="--save"
if [[ "$1" == "--save" ]]; then
    shift
elif [[ "$1" == "--check" ]]; then
    action="--check"
    shift
fi

# No arguments: Csum current dir to stdout. One argument: Csum to stdout. Two+ arguments: last is csum file.

if [[ "$#" == "0" ]]; then
    pathsToCsum=(".")
    checksumFile=""
elif [[ "$#" == "1" ]]; then
    pathsToCsum=("$1")
    checksumFile=""
else
    pathsToCsum=("${@:1:$(($#-1))}") # all but last argument
    checksumFile="${!#}" # last argument
fi

if [[ "$checksumFile" == "-" ]]; then
    checksumFile=""
fi

case $action in
--save)
    setVariableToCommandOutput currentworkingdir pwd -P
    currentworkingdir="${currentworkingdir:?}"
    currentworkingdir="${currentworkingdir//$'\n'/'\n'}"
    myArguments=( "$@" )
    # Do two passes to make sure nothing changed while reading and there weren't other errors
    # First pass
    firstPass="$(tempFile)"
    {
        echo "ac21539a-427e-499e-9f6b-eb079ca528f1"
        printf '%s\n' "${currentworkingdir//$'\r'/'\r'}"
        for arg in "${myArguments[@]}"; do
            printf '%s`' "$(base64 <<< "$path")"
        done
        printf '\n'
        temp="$(tempFile)"
        for path in "${pathsToCsum[@]}"; do
            hashdeep -c md5,sha1,sha256,tiger,whirlpool -j0 -e -o fbsd -r -l "$path" > "$temp"
            setVariableToCommandOutput tempDirname eescape "$(dirname "$path")/"
            ereplaceRegEx "(\\d+,([a-f\\d]+,){5})${tempDirname:?}" '$1' "$temp"
            cat "$temp"
        done
        rm "$temp"
    } > "$firstPass"
    # Second pass
    secondPass="$(tempFile)"
    {
        echo "ac21539a-427e-499e-9f6b-eb079ca528f1"
        printf '%s\n' "${currentworkingdir//$'\r'/'\r'}"
        for arg in "${myArguments[@]}"; do
            printf '%s`' "$(base64 <<< "$arg")"
        done
        printf '\n'
        temp="$(tempFile)"
        for path in "${pathsToCsum[@]}"; do
            hashdeep -c md5,sha1,sha256,tiger,whirlpool -j0 -e -o fbsd -r -l "$path" > "$temp"
            setVariableToCommandOutput tempDirname eescape "$(dirname "$path")/"
            ereplaceRegEx "(\\d+,([a-f\\d]+,){5})${tempDirname:?}" '$1' "$temp"
            cat "$temp"
        done
        rm "$temp"
    } > "$secondPass"
    assert fileEquals "$firstPass" "$secondPass" || { cat "$firstPass"; cat "$secondPass"; die }
    if [[ -z "$checksumFile" ]]; then
        cat "$firstPass"
        rm "$firstPass"
    else
        mv "$firstPass" "$checksumFile"
    fi
    rm "$secondPass"
    ;;
--check)
    streamId="csum-$(date-uuid)"

    finish() {
        if [[ -e "/tmp/${streamId:?}" ]]; then
            rm "/tmp/${streamId:?}"
        fi
    }
    trap 'error-notify "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."; finish; exit 1' ERR
    trap finish EXIT

    if [[ -z "$checksumFile" ]]; then
        sponge "/tmp/$streamId"
        tail -n +2 < "/tmp/$streamId" | sponge "/tmp/$streamId"
    else
        tail -n +2 "$checksumFile" > "/tmp/$streamId"
    fi

    hashdeep -k "/tmp/$streamId" -e -o fbsd -r -l -a -v -v "${pathsToCsum[@]}"
    finish
    ;;
*)
    echo "Unknown action."
    exit 1
    ;;
esac
