#!/usr/bin/env bash
#set -x

# Should work without ember-shared or crystallize, just in case, so don't set traps or source ember_bash_setup

configFileLocation="/usr/local/etc/ember.conf"

if [[ "$1" == "ConfigLocation" ]]; then
    echo "$configFileLocation"
    exit
fi

if [[ "$1" == "ConfigDir" ]]; then
    dirname "$(readlink -f "$(ember-getconf ConfigLocation)")"
    exit
fi

if [[ "$1" == "DataDir" ]]; then
    echo ""$(dirname "$(ember-getconf ConfigLocation)")"/../share/ember/"
    exit
fi

if [[ "$1" == "crystallizeVersion" ]]; then
    crystallizeVersionA="$(sed '18q;d' "$(which crystallize)")" || exit 1
    crystallizeVersionB="${crystallizeVersionA%\'*}"
    echo "${crystallizeVersionB##*\'}"
    exit
fi

if [[ "$1" == "emberSharedVersion" ]]; then
    # shellcheck disable=SC2034
    e8787d06e61943a6874e94985b53bc0a="2dee41bf-53fb-4f65-997f-33bf50bfbb4d"; ember_bash_setup --version
    exit
fi

if [[ "$1" == "WorkDirectory" ]]; then
    if [[ -v EmberWorkdirOverride54ae685dc782437c99bc46c7a1211377 ]]; then
        if [[ -n "${EmberWorkdirOverride54ae685dc782437c99bc46c7a1211377:?}" ]]; then
            printf '%s' "$EmberWorkdirOverride54ae685dc782437c99bc46c7a1211377"
            exit
        fi
    fi
fi

if [[ "$1" == "BackupLocation" ]]; then
    if [[ "$(ember-getconf BackupInWorkdir)" == "true" ]]; then
        backupLocation="$(ember-getconf WorkDirectory)/$(ember-getconf RelativeBackupLocation)"
    else
        backupLocation="$(ember-getconf RelativeBackupLocation)"
    fi
    printf '%s\n' "$backupLocation"
    exit
fi

grep -n ^"$1", "$configFileLocation" | cut -f2 -d: | tail -1 | cut -f2 -d,
