#!/usr/bin/env bash

#set -x

trap 'warn "A nonfatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR
brew install coreutils findutils gnu-tar gnu-sed gawk gnutls gnu-indent gnu-getopt wdiff wget gawk bash
