#!/usr/bin/env bash
#set -x

# Should work without ember-shared or crystallize, just in case, so don't set traps or source ember_bash_setup

configFileLocation="/usr/local/etc/ember.conf"

if [[ "$1" == "ConfigLocation" ]]; then
    echo "$configFileLocation"
    exit
fi

if [[ "$1" == "ConfigDir" ]]; then
    dirname "$(readlink -f "$(ember-getconf ConfigLocation)")"
    exit
fi

if [[ "$1" == "crystallizeVersion" ]]; then
    crystallizeVersionA="$(sed '18q;d' "$(which crystallize)")" || exit 1
    crystallizeVersionB="${crystallizeVersionA%\'*}"
    echo "${crystallizeVersionB##*\'}"
    exit
fi

if [[ "$1" == "WorkDirectory" ]]; then
    if [[ -v CrystalWorkdirOverride54ae685dc782437c99bc46c7a1211377 ]]; then
        if [[ -n "${CrystalWorkdirOverride54ae685dc782437c99bc46c7a1211377:?}" ]]; then
            printf '%s' "$CrystalWorkdirOverride54ae685dc782437c99bc46c7a1211377"
            exit 0
        fi
    fi
fi

grep -n ^"$1", "$configFileLocation" | cut -f2 -d: | tail -1 | cut -f2 -d,
