#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd)."' ERR

packageName="$1"
shift

# Note: Only provide this file if the package should run on macOS. Your code may require some
# changes to be correctly transformed by this script.

fail() {
    #NOTE: MAINTENANCE: Manual error printing
    if [[ -z "$(ember-getconf emberSharedVersion)" ]]; then
        printf '%b' '\033[1;31m' >&2
        echo "ERROR: ember-shared is not properly installed! It must be installed before installing $packageName." >&2
        printf '%b' '\033[0m' >&2
        exit 1
    fi
}

if [[ -z "$(ember-getconf emberSharedVersion)" ]]; then
    fail
fi

if [[ "$OSTYPE" = darwin* ]]; then
    if [[ -f "support/prepareForMac" ]]; then
        support/prepareForMac "$packageName"
    fi
fi
