#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

# Use: findq-update pathToIndex extra-options-for-updatedb...

pathToIndex="$(realpath "$1")"
shift

dbFile="$(sha512sum <<< "$pathToIndex" | awk '{print $1;}')"

mkdir -p ~/.findq

cd ~/.findq

# based on man updatedb
updatedb -l 0 -o "./databases/$dbFile" -U "$pathToIndex" "$@"

eogup-single
